CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID               UUID PRIMARY KEY,
    EMAIL            VARCHAR(255) NOT NULL UNIQUE,
    NOME_COMPLETO    VARCHAR(300) NOT NULL,
    CPF              VARCHAR(20) UNIQUE,
    TELEFONE         VARCHAR(20),
    EMAIL_VERIFICADO BOOLEAN   DEFAULT FALSE,
    HABILITADO       BOOLEAN   DEFAULT TRUE,
    ALTERAR_SENHA    BOOLEAN   DEFAULT FALSE,
    DH_CRIACAO       TIMESTAMP DEFAULT NOW(),
    DH_ALTERACAO     TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IDX_CLIENTES_NOME ON CLIENTES(NOME_COMPLETO);

COMMENT ON TABLE CLIENTES IS 'REGISTRO DOS CLIENTES CADASTRADOS NO SISTEMA';
COMMENT ON COLUMN CLIENTES.ID IS 'IDENTIFICADOR ÚNICO DO CLIENTE';
COMMENT ON COLUMN CLIENTES.EMAIL IS 'EMAIL DO CLIENTE';
COMMENT ON COLUMN CLIENTES.NOME_COMPLETO IS 'NOME COMPLETO DO CLIENTE';
COMMENT ON COLUMN CLIENTES.CPF IS 'CPF DO CLIENTE';
COMMENT ON COLUMN CLIENTES.TELEFONE IS 'TELEFONE PRINCIPAL DO CLIENTE';
COMMENT ON COLUMN CLIENTES.EMAIL_VERIFICADO IS 'TRUE = EMAIL VERIFICADO, FALSE = NÃO VERIFICADO';
COMMENT ON COLUMN CLIENTES.HABILITADO IS 'TRUE = HABILITADO, FALSE = DESABILITADO';
COMMENT ON COLUMN CLIENTES.ALTERAR_SENHA IS 'TRUE = DEVE ALTERAR SENHA, FALSE = NÃO PRECISA ALTERAR';
COMMENT ON COLUMN CLIENTES.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN CLIENTES.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';

